### ISSUE TITLE
[Help document bug] For dwarfdump, the help document misses some options

### ISSUE THREAD

**Issue by ccccmd** [davea42/libdwarf-code#146]
The "--help" option of dwarfdump misses some options "print-frame", "trace" for version 0.5.0.

For the option "print-frame", the following code appears during option parsing and calls the  arg_print_debug_frame() in src/bin/dwarfdump/dd_command_options.c:2705 for version 0.5.0.

```
                case OPT_PRINT_FRAME:       arg_print_debug_frame(); break;
```

For the option "trace", the following code appears during option parsing and calls the  arg_trace() in src/bin/dwarfdump/dd_command_options.c2769 for version 0.5.0.

```
                case OPT_TRACE: arg_trace(); break;
```

But it does not appear in the document provided by "--help".

It may prevent users from using the relevant function.

**Comment by davea42** [comment]
Thanks for the note.  We're still recovering from power outages recently... one was 4 full days long.

**Comment by davea42** [comment]
The omission of -f  and --print-frame was a major botch.  Pushed the fix.

The omission  of   -# and  --trace=<num> 
was intentional as it's only useful for debugging
issues in -k (checking )options.
--trace=0 
will show the other values available but it's quite useless information.
I see no reason to include it in the help text.

Thanks again for the note.

**Comment by davea42** [comment]
Fixed, so closing. Thanks again.
