### ISSUE TITLE
I want to develop under Windows, compile with msvc, how to compile to static library .lib and dynamic library .dll files?thanks

### ISSUE THREAD

**Issue by lovecomputer88** [davea42/libdwarf-code#172]
I see that there is Release libdwarf 0.7.0, I want to develop under Windows, compile with msvc, how to compile to static library .lib and dynamic library .dll files?thanks

**Comment by davea42** [comment]
Well, building 0.7.0 with meson will let you build a libdwarf.a (static library)
or .dll  .
Using the current state (top of main on github) 0.7.1 will also
let you use meson to build a libdwarf.a or  .dll

See README.md for how to use mingw64 msys2 for build instructions 
We suggest using meson and ninja, which can build a .a or a  .dll  (with either 0.7.0
or unreleased 0.7.1 source)

Exactly how one uses such a built libdwarf.a or a libdwarf.dll
with msvc...I do not know.   Sorry.

**Comment by vtorri** [comment]
@lovecomputer88  there is the possibility with meson to create a Visual Studio solution:

1) be sure to have meson installed (with python : `pip install meson` should be sufficient
2) in cmd.exe, run: 

```
meson setup --backend vs --buildtype=debug --default-library both builddir_vs
```

change buildtype to have debug symbols or not (`--buildtype=release` to remove debug symbols)

the Visual Studio solution will be in the `builddir_vs` directory

**Comment by watkipet** [comment]
I compiled libdwarf as a static library with msvc using CMAKE:

1.  Install CMake. You can manually download it and install it. If you use chocolatey, that can just do:  `choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'`
2. Make a cmake build directory alongside the code directory: `mkdir libdwarf-build`
3. CD into that directory: `cd libdwarf-build`
4. Run CMake to generate a Visual Studio 2022 solution: `cmake -G "Visual Studio 17 2022" ..\libdwarf-code`
5. Either open the solution in Visual Studio 2022 or build it with msbuild. To build with msbuild, run: `msbuild libdwarf.sln`

Unfortunately, `libdwarf.h` has this line: `#define DWP_API __declspec(dllimport)`. This means that when `dwarfdump` or any other project uses that header, it assumes that all the functions are in a DLL. They aren't because I compiled libdwarf as a static library, not a DLL. The only way I've found to hack around this is to trick the header file by defining LIBDWARFP_BUILD at compile-time. I.e. first I run `set CL=/DLIBDWARF_BUILD`, then I run `msbuild libdwarf.sln`

**Comment by vtorri** [comment]
you HAVE to pass LIBDWARF_STATIC to the preprocessor

**Comment by davea42** [comment]
Since vtorri correctly pointed out that the preprocessor must see  LIBDWARF_STATIC
whenever  one  includes libdwarf.h  when  linking with a static library, I rather think
this can be closed.    I'll wait till early next week in case more advice is needed.

**Comment by lovecomputer88** [comment]
How do I use LIBDWARF_STATIC? Please give an example, thanks

**Comment by vtorri** [comment]
to pass `LIBDWARF_STATIC` to the preprocessor with Visual Studio:

1. right click on a project name
2. in the contextual menu, click on `Properties`  at the very bottom
3. in the new window, double click on `C/C++`
4. on the right, click on `Preprocessor definitions`
5. the is a small down arrow on the right, click on it, then  click on `Modify`
6. add  `LIBDWARF_STATIC` to the values
7. click on `OK` to close the windows

**Comment by davea42** [comment]
I have updated README.md  and  the doxygen document to document
the need for LIBDWARF_STATIC when compiling code calling
libdwarf.a  (static library).  The doxygen  now shows the method as  vtorri
describes it above, see 

Linking against libdwarf.a

in the html/pdf documentation.
