### ISSUE TITLE
Symbolic relocations for line numbers

### ISSUE THREAD

**Issue by Victorious3** [davea42/libdwarf-code#205]
Curiously I found this line in the documentation: 
```
Line number operations do not support DW_DLC_SYMBOLIC_RELOCATIONS
```
Since I'm only using symbolic relocations, this looks like a bit of a showstopper for me right now.
My question is, what would need to be done to make this work? I've already looked at the sourcecode of libdwarfp a bit and maybe I could help implementing this.

What's happening right now is that I get the wrong `drd_offset` and I can no longer look at the initial value to calculate the addend for the relocations. The section sizes (`.debug_info`) seem a bit suspicious. Somehow it gets smaller when I add the line numbers.

I'm currently testing the library to use it for my compiler project later. I'm trying to combine two object files into a single one.
This involves reading the information with libdwarf into a tree structure and then outputting the whole thing again. 

The tricky part is that I need to modify the debug information because I want to replace a function from the first object file with one from the second one. So I need to completely remove the debug information for the first function.

**Comment by davea42** [comment]
Well, if you look at dwarf_pro_section you will find that
dbg->de_relocate_by_name_symbol =
            _dwarf_pro_reloc_name_symbolic; and it is used for symbolic relocations in the .debug_line section.


The comment in libdwarfp.mm may mean something or maybe is just wrong.

I am more than a little bit confused how you are storing the content of a CU and its functions
so you can write them out.  Are you going direct from reading with libdwarf do writing with libdwarfp?
Or have you written your own code to save in memory and *then* calling (for
exmple) libdwarfp  with add_line_entry
sort of call for line number details?

Anyway, aside from my confusion:


drd_offset is supposed to be the section offset of an item requiring relocation. For DW_LNE_set_address
libdwrfp writes the address then calls 

```
 dbg->de_relocate_by_name_symbol(dbg,
                    DEBUG_LINE,
                    sum_bytes,  /* r_offset  */
                    curline->dpl_r_symidx,
                    dwarf_drt_data_reloc,
                    offset_size);

```
which is 
`_dwarf_pro_reloc_name_symbolic()`
which does
```
    res = _dwarf_pro_reloc_get_a_slot(dbg, base_sec_index,
        &relrec_to_fill);
    if (res != DW_DLV_OK)
        return res;
    slotp = (struct Dwarf_Relocation_Data_s *) relrec_to_fill;
    slotp->drd_type = type;
    slotp->drd_length = reltarget_length;
    slotp->drd_offset = offset;
    slotp->drd_symbol_index = symidx;
    return DW_DLV_OK;
}
```

The offset is an offset in .debug_line.  Since a line table covers all lines for all functions in a CU
it might be challenging to  replace parts of a table.  I am not attempting to explain incorrect drd_offset,
as I not understand what is wrong or why you are sure offsets are wrong.

The definition of the line table says that it is a table with strictly increasing pc address,
and with data present in the table where the content  of the line for address 0x101 differs from 
that in line for address 0x100.

So one would have to find the series of line entries corresponding to the function being removed
and remove them If the new function covers more code addresses than the old...there is a problem
to be addressed (something to think about)!
If it covers fewer or the same pc range as the old, one could replace the old set with the
new set.

Sorry, but I have no simple answer. I just want to be sure you are seeing the issues.
DavidA

**Comment by Victorious3** [comment]
I've written something to store the DIEs and the attributes in a tree structure before writing.

Maybe it's an incorrect sequence? I call `dwarf_add_line_entry_c` in a loop whenever an attribute of the type DW_AT_stmt_list gets transformed from my representation to a Dwarf_P_Die. This happens before the call to `dwarf_transform_to_disk_form_a`

What's really strange is that the call to `dwarf_get_section_bytes_a` results in a size for the `.debug_info` section which is *smaller* than when I don't call `dwarf_add_line_entry_c`. The incorrect offsets might just be a symptom of that.

My debug prints look like this:
```
Section .debug_info new size 56
Section .debug_info new size 94
```
compared to when I don't add the lines:
```
Section .debug_info new size 175
Section .debug_info new size 273
```
I don't think that's supposed to happen when I add in fact add more data?

I would link my code here but it's not written in C but in a custom programming language.

I think the comment meant that there are no symbolic relocations for the `.debug_line` section, which I can confirm. I only get those for the `.debug_info` section.

**Comment by Victorious3** [comment]
I've found the problem, I was using the wrong section index.

I think the comment meant that there are no relocations for the `.debug_line` sections, which does seem to be the case for me.
