### ISSUE TITLE
provide a version for the tarballs, named accordingly

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#6]
You should (must ?) provide a version for libdwarf, normally in the .pc file (see #4 )

The version should follow this scheme:

- version has 3 components : major, minor and micro
- start with major=minor=micro=0
- before doing a release:
  - if bug is fixed, increase minor
  - if an API is added, minor = 0 and increase minor
  - if an API is changed or removed, or if ABI is changed, minor = micro=0, and increase major

the tarbal should be named like that : libdwarf-maj.min.mic.tar with maj, min and mic being the major, minor and micro version

this way, people knows what happened to a new tarbal, you can also change or modify API and install the new libdawrf in another dir

like install libdrawf header files in $prefix/libwarf-maj/

So if you change API, libdwarf header files from different major versions will be able to co-habit

**Comment by davea42** [comment]
Much as I like the dated (YYYYMMDD) releases in current  use the 
dated approach completely fails to address the question
"what sort of things changed between this and that release?"

So far we've avoided changing any API since at least 2013 (and that only involved the 
libdwarf producer (ie writing dwarf) and that producer
code is now only really very useful in producing test objects
for things in DWARF that no compiler yet does (very few such cases exist).

We do add new functions from time to time.

Users would have to be warned well  in advance.
This deserves consideration.

**Comment by davea42** [comment]
This is covered in dwarf.html#future so closing this here.
